export const APP_ROUTES={
  EMPTY_ROUTE:"",
  LAYOUT:"pages",
  HOME : "home",
  DASHBOARD : "dashboard",
  LOGIN : "login",
  RLOGIN : "login-rform",
  Register : "register-user",
  Villas:"indexVillas",
  CreateVilla:"createVilla",
  EditVilla:"createVilla/:id",
  VillaNumber:"indexVillaNumbers",
  CreateVillaNumbers:"createVillaNumbers",
  EditVillaNumbers:"editVillaNumbers/:id",
}
